package com.keyin.domain.types;

public enum SurgeryTypes {
  CATARACT,
  ARTHROSCOPY,
  HERNIA_REPAIR,
  APPENDECTOMY,
  HYSTERECTOMY,
  CHOLECYSTECTOMY,
  CESAREAN_SECTION,
  TONSILLECTOMY,
  KNEE_REPLACEMENT,
  HIP_REPLACEMENT,
  CORONARY_ARTERY_BYPASS_GRAFT,
  ANGIOPLASTY,
  MASTECTOMY,
  LUMPECTOMY,
  PROSTATECTOMY
}
